# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76703be923f1006e06fe81b05660926c7f04f52e29bf1526605b5c60e12cf5c8f37ed199f0117e166f821ba643e63b083fea440c6ffa132b6f6f5a0a46a9cd3c

test:
  secret_key_base: 7abcb8720cbd311ff5132f86049d54b16d44d4414fbbe19e4c289d2614db01d55b603494757809d08514ba6987a084a3bb236f06f8a9269c430a893ab1f4fb82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
